---
name: Create Tag on Pull Request Merge
on:
  pull_request:
    types: closed

jobs:
  tag_merged_pr:
    name: Create Tag on PR Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag Change
        run: |
          set -ex
          #git fetch tags
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          #fetch latest semvar tag
          latest_version_full="$(git tag | sort -r --version-sort | head -n1)"
          #parse semvar version - remove env and leading v
          latest_version_full=${latest_version_full#"v"}
          version_full=( ${latest_version_full//-/ } )
          version="${version_full[0]}"
          echo "$version"
          #version_array=($(echo $version|tr "\." "\n"))
          IFS='.' read -r -a version_array <<< "$version"
          #bump by patch version, add patch version if doesn't exist
          if [ ${#version[@]} -ne 3 ]
          then
            version_array+=(0)
          fi
          ((version_array[2]++))
          # build version from array
          new_version="v${version_array[0]}.${version_array[1]}.${version_array[2]}-DEV"
          commit_sha="${{ github.sha }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "$new_version" "$commit_sha"
          git push --tags
