---
name: Pull Request Labler
on:
  pull_request:
    types: [closed]

jobs:
  label_pull_request:
    name: Add Code Label To Pull Request
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  label_pull_request_tag:
    name: Add Tag Label To Pull Request
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request - Tag
        run: |
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/labels" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACCESS_TOKEN }} \
            -d '{ "name": "'"${{ github.head_ref }}"'", "color": "b2d8d8" }'
          curl -X POST "${{ github.event.pull_request.head.repo.issues_url }}/labels" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACCESS_TOKEN }} \
            -d '{ "labels": [ "'"${{ github.head_ref }}"'" ] }' \
             --verbose
